# Generated by Django 5.2.6 on 2025-09-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_habitacion', '0001_initial'),
        ('app_huesped', '0001_initial'),
        ('app_tarifa_habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitacionReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_ars', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_habitacion.habitacion')),
                ('moneda_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_tarifa_habitacion.moneda')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_tarifa_habitacion.tarifa')),
            ],
        ),
        migrations.CreateModel(
            name='HuespedHabitacionReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huespedes', to='app_reserva.habitacionreserva')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_huesped.huesped')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('checkin', 'Check-in'), ('checkout', 'Check-out'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='app_huesped.huesped')),
            ],
        ),
        migrations.AddField(
            model_name='habitacionreserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones_reservadas', to='app_reserva.reserva'),
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarifa_habitacion.moneda')),
            ],
            options={
                'unique_together': {('fecha', 'moneda')},
            },
        ),
    ]
