# Generated by Django 5.2.6 on 2025-09-12 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_habitacion', '0001_initial'),
        ('app_huesped', '0002_rename_documento_huesped_numero_documento_and_more'),
        ('app_reserva', '0001_initial'),
        ('app_tarifa_habitacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huespedhabitacionreserva',
            name='habitacion_reserva',
        ),
        migrations.RemoveField(
            model_name='huespedhabitacionreserva',
            name='huesped',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='reservante',
        ),
        migrations.AddField(
            model_name='reserva',
            name='huesped_reservante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_realizadas', to='app_huesped.huesped'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_ars', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_habitacion.habitacion')),
                ('moneda_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_tarifa_habitacion.moneda')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='app_reserva.reserva')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_tarifa_habitacion.tarifa')),
            ],
        ),
        migrations.CreateModel(
            name='HuespedReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_huesped.huesped')),
                ('reserva_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huespedes', to='app_reserva.reservahabitacion')),
            ],
        ),
        migrations.DeleteModel(
            name='HabitacionReserva',
        ),
        migrations.DeleteModel(
            name='HuespedHabitacionReserva',
        ),
    ]
