# Generated by Django 5.2.6 on 2025-09-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Canal de Venta',
                'verbose_name_plural': 'Canal de Ventas',
            },
        ),
        migrations.CreateModel(
            name='ModalidadTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Por habitación, Por persona', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Modalidad de tarifa',
                'verbose_name_plural': 'Modalidades de tarifa',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('temporada', models.CharField(blank=True, max_length=50, null=True)),
                ('canal_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='app_tarifa_habitacion.canalventa')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='app_tarifa_habitacion.modalidadtarifa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='app_tarifa_habitacion.moneda')),
                ('tipo', models.ForeignKey(help_text='Tipo de habitación al que aplica esta tarifa', on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='app_habitacion.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'unique_together': {('tipo', 'canal_venta', 'modalidad', 'moneda', 'temporada')},
            },
        ),
    ]
