# Generated by Django 5.2.6 on 2025-09-12 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModalidadTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_ars', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('canal_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarifa_habitacion.canalventa')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarifa_habitacion.modalidadtarifa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_tarifa_habitacion.moneda')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_habitacion.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarifa_habitacion.moneda')),
            ],
            options={
                'unique_together': {('moneda', 'fecha')},
            },
        ),
    ]
