# Generated by Django 5.2.6 on 2025-09-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_huesped', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huesped',
            old_name='documento',
            new_name='numero_documento',
        ),
        migrations.AlterField(
            model_name='huesped',
            name='estado',
            field=models.CharField(choices=[('RESERVANTE', 'Reservante'), ('OCUPANTE', 'Ocupante')], default='RESERVANTE', max_length=20),
        ),
    ]
