# Generated by Django 5.2.6 on 2025-09-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('piso', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('EN MANTENIMIENTO', 'En mantenimiento'), ('RESERVADA', 'Reservada'), ('LIMPIEZA', 'Limpieza'), ('BAJA', 'Baja'), ('SIN USO', 'Sin uso')], default='DISPONIBLE', max_length=20)),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='app_habitacion.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
